import {
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarDays,
  CandlestickChart,
  ChartSpline,
  Code2,
  Copy,
  Globe2,
  GraduationCap,
  Handshake,
  Landmark,
  MessagesSquare,
  Newspaper,
  PieChart,
  ScanFace,
  Smartphone,
  Trophy,
  Wallet,
  Target,
  type LucideIcon,
} from "lucide-react";
import type { BrkModuleKey } from "@kalks/mock/admin-platform-brokers";

/** One icon per module (the gateway's module keys, tenancy.rs, plus the showcase's plan-only items). */
export const MODULE_ICON: Record<BrkModuleKey, LucideIcon> = {
  trading: CandlestickChart,
  wallet: Wallet,
  ib: Handshake,
  copy_trading: Copy,
  pamm: PieChart,
  mam: BriefcaseBusiness,
  prop: Target,
  rewards: Trophy,
  academy: GraduationCap,
  ai: Brain,
  api: Code2,
  algo: Bot,
  options: ChartSpline,
  news: Newspaper,
  calendar: CalendarDays,
  markets: Globe2,
  support_chat: MessagesSquare,
  stocks: Landmark,
  mobile: Smartphone,
  kyc_auto: ScanFace,
};
