// Writes packages/ui/src/tokens.css from packages/ui/src/tokens.ts (Kalks 2 tokens, one source of truth).
// Run after changing tokens.ts: `pnpm --filter @kalks/ui tokens` (Node ≥ 23 strips the TypeScript types).
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ACCENTS, BRAND, CONSTANTS, LEGACY, ROLES } from "../src/tokens.ts";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "tokens.css");

const decl = (entries, indent) => entries.map(([k, v]) => `${indent}--k-${k}: ${v};`).join("\n");
const theme = (i, indent) => decl([...Object.entries(ROLES), ...Object.entries(LEGACY)].map(([k, pair]) => [k, pair[i]]), indent);

const css = `/* GENERATED by packages/ui/scripts/gen-tokens.mjs from src/tokens.ts: edit tokens.ts, then run
   \`pnpm --filter @kalks/ui tokens\`. Kalks 2 colour tokens (docs/design/KALKS2.md §2).
   Three states: Auto follows the OS; data-theme="light|dark" (or the .light / .dark class) on <html> or on any
   element overrides it for that subtree. */

/* brand constants and the accent families a white-label broker replaces (brandCss, shell/brand-vars.ts) */
:root {
${decl(Object.entries(BRAND), "  ")}
${decl(Object.entries(ACCENTS), "  ")}
${decl(Object.entries(CONSTANTS), "  ")}
}

/* light: the base */
:root,
[data-theme="light"],
.light {
  color-scheme: light;
${theme(0, "  ")}
}

/* Auto: the OS asks for dark */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not(.light) {
    color-scheme: dark;
${theme(1, "    ")}
  }
}

/* Dark chosen (or a subtree forced dark) */
[data-theme="dark"],
.dark {
  color-scheme: dark;
${theme(1, "  ")}
}
`;

writeFileSync(out, css);
console.log(`tokens.css written (${Object.keys(ROLES).length} roles, ${Object.keys(LEGACY).length} legacy aliases)`);
